//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedSale
    {
        public long DetailedSaleID { get; set; }
        public short Quantity { get; set; }
        public long InventoryID { get; set; }
        public decimal SellingPrice { get; set; }
        public long InvoiceID { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
