//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.AccountBalances = new HashSet<AccountBalance>();
            this.DetailedSales = new HashSet<DetailedSale>();
            this.InventoryIns = new HashSet<InventoryIn>();
        }
    
        public long InventoryID { get; set; }
        public string ProductName { get; set; }
        public int CategoryID { get; set; }
        public int StockQuantity { get; set; }
        public int LastEditedby { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal BuyingPrice { get; set; }
    
        public virtual ICollection<AccountBalance> AccountBalances { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<DetailedSale> DetailedSales { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<InventoryIn> InventoryIns { get; set; }
    }
}
